# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - main
    types:
      - completed

jobs:
  copy_repository:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Copy repository to specific folder
      run: |
        robocopy ${{ github.workspace }} "C:\Users\mafeeslv\Documents\CarpetaPipeline" /S

