on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env: 
      # set apppool and site name from IIS
      AppPoolName : PruebaPL
      SiteName  : 'PruebaPL'
      SitePublishName  :  'PruebaPL'
      # set to site files.  In this case, the part of the path after f:/websites/
      SitePath :  C:\PruebaPL

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build --configuration Release .

      - name: dotnet publish 
        run: | 
          dotnet publish -c Release -o ${{env.SitePublishName}}Publish .
    
      - name: Sleep for 5 seconds
        run: Start-Sleep -s 5 

      - name: Deploy to IIS
        run: |
          stop-webapppool {AppPoolName}
          stop-iissite -Name {SiteName} -Confirm: $false
          Copy-Item ./${{env.SitePublishName}}Publish/* 'C:\PruebaPL' -Recurse -Force 
          $success = $true;
          start-webapppool {AppPoolName}
          start-iissite {SiteName}
          
